"""empty message

Revision ID: 7bfdc7311590
Revises: 
Create Date: 2019-03-06 09:13:27.638586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfdc7311590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_info1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('lng', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.String(length=255), nullable=True),
    sa.Column('speed', sa.String(length=255), nullable=True),
    sa.Column('money', sa.Float(), nullable=False),
    sa.Column('feescale', sa.Float(), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_code', sa.String(length=255), nullable=False),
    sa.Column('money', sa.Float(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('bus1_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bus1_id'], ['bus_info1.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bus_id'], ['bus_info.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_bus1_id'), 'order', ['bus1_id'], unique=False)
    op.create_index(op.f('ix_order_bus_id'), 'order', ['bus_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_bus_id'), table_name='order')
    op.drop_index(op.f('ix_order_bus1_id'), table_name='order')
    op.drop_table('order')
    op.drop_table('bus_info1')
    # ### end Alembic commands ###
